### ISSUE TITLE
[intro-to-pytorch] Rename helper module to avoid conflicts with python's built-in helper

### ISSUE THREAD

**Issue by jaintj95** [udacity/deep-learning-v2-pytorch#107]
Literally every person in the course has had issues with loading/working with the helper.py module because the one provided here conflicts with python's built-in helper module. 
The module should be renamed to something like helper_mod.py and the corresponding imports renamed in all notebooks to avoid this conflict.

**Comment by randallsalvares** [comment]
@jaintj95 please if you can provide the instructions of installing and using the helper module used in "intro to pytorch" course as you mentioned above. I am sure many like me are struggling to use this module.

**Comment by jaintj95** [comment]
@randallsalvares You need to restart your kernel/session and then rerun the cell which imports helper. Also make sure the helper.py module is present in your local workspace. You can download it from the repo here

**Comment by randallsalvares** [comment]
Thanks for the quick help out @jaintj95 . I managed to solve this issue. 
The helper.py file was in my  intro-to-pytorch folder when I had downloaded this repo.
With a quick upload in my jupyter workspace this issue was sorted.
Thanks Again!!
