### ISSUE TITLE
[style_transfer_excercise] VGG model print statement is commented

### ISSUE THREAD

**Issue by virresh** [udacity/deep-learning-v2-pytorch#114]
Probably a small miss 

At https://render.githubusercontent.com/view/ipynb?commit=92534a85ac795dc493525b095e0ac72c7789bb9e&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f756461636974792f646565702d6c6561726e696e672d76322d7079746f7263682f393235333461383561633739356463343933353235623039356530616337326337373839626239652f7374796c652d7472616e736665722f5374796c655f5472616e736665725f45786572636973652e6970796e62&nwo=udacity%2Fdeep-learning-v2-pytorch&path=style-transfer%2FStyle_Transfer_Exercise.ipynb&repository_id=147386085&repository_type=Repository#VGG19-Layers 
The lines where we are supposed to inspect VGG19 layers is commented.
Although we do get to see the structure anyways when running the notebook from start and moving vgg model to gpu, but it'd be helpful to either mention this explicitly over there or uncomment this line

Would be happy to send in  a PR if seems relevant to others.

**Comment by jchernus** [comment]
As you said, the model structure is displayed earlier in the notebook. Those students wishing to see this information again can uncomment the line of code, while most students opt into skipping this.
