### ISSUE TITLE
cifar10_cnn_solution Error in section 'Visualize Sample Test Results' when training on GPU

### ISSUE THREAD

**Issue by Michael-Schulze** [udacity/deep-learning-v2-pytorch#121]
Using `train_on_gpu = True` leads to 

> TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

```
# plot the images in the batch, along with predicted and true labels
fig = plt.figure(figsize=(25, 4))
for idx in np.arange(20):
    ax = fig.add_subplot(2, 20/2, idx+1, xticks=[], yticks=[])
    imshow(images[idx])
    ax.set_title("{} ({})".format(classes[preds[idx]], classes[labels[idx]]),
                 color=("green" if preds[idx]==labels[idx].item() else "red"))
```

Missing `.cpu()` in `imshow(images[idx])`

Should be

```
# plot the images in the batch, along with predicted and true labels
fig = plt.figure(figsize=(25, 4))
for idx in np.arange(20):
    ax = fig.add_subplot(2, 20/2, idx+1, xticks=[], yticks=[])
    imshow(images.cpu()[idx])
    ax.set_title("{} ({})".format(classes[preds[idx]], classes[labels[idx]]),
                 color=("green" if preds[idx]==labels[idx].item() else "red"))
```

**Comment by cezannec** [comment]
Thank you! This has been fixed

**Comment by marcindulak** [comment]
Please reopen: the problem has been fixed in the solution notebook, but not in the exercise https://github.com/udacity/deep-learning-v2-pytorch/blob/3a95d118f9df5a86826e1791c5c100817f0fd924/convolutional-neural-networks/cifar-cnn/cifar10_cnn_exercise.ipynb

When closing issues please refer to pull requests so the changes can be tracked.

**Comment by rogalskim** [comment]
I've created a new issue for the problem in the **exercise** notebook, since technically this issue was only for the **solution** file.

**Comment by Sturzgefahr** [comment]
This is also an issue in the file **cifar10_cnn_augmentation**.
