### ISSUE TITLE
Subsampling probabilties go negative

### ISSUE THREAD

**Issue by pisymbol** [udacity/deep-learning-v2-pytorch#123]
In the word2vec-embedding module, the subsampling probabilities go negative which makes no sense to me: See here:

`{5233: 0.25803314192489146, 3080: 0.4599825339524992, 11: 0.9644267615025448, 5: 0.9773753623879587, 194: 0.8479917006734952, 1: 0.9832378119313352, 3133: 0.45568334430257695, 45: 0.9239088422795724, 58: 0.9143476584471071, 155: 0.8593497455736082, 127: 0.8719431999366315, 741: 0.7289825504731466, 476: 0.778893601917191, 10571: -0.19915915224535286, 133: 0.8684093473492618, 0: 0.9874637657774047, 27349: -1.5830678659299684, 102: 0.8814457705299201, 854: 0.7132755043218617, 2: 0.9799907379071721, 15067: -0.5662149484364791, 58112...`

That's a partial dump of p_drop. Why are their negative probabilities?

**Comment by zzyxzz** [comment]
The subsampling equation shows that it isn't really a probability. If the threshold parameter in the equation is not properly set, the value can be negative. To me, it's more like a score rather than probability.

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you
