### ISSUE TITLE
[project-tv-script-generation] wrong parameter names in doc for forward_back_prop

### ISSUE THREAD

**Issue by janmande** [udacity/deep-learning-v2-pytorch#124]
The documentation comments for the first two parameters to the function forward_back_prop have wrong names:

```python
def forward_back_prop(rnn, optimizer, criterion, inp, target, hidden):
    """
    Forward and backward propagation on the neural network
    :param decoder: The PyTorch Module that holds the neural network
    :param decoder_optimizer: The PyTorch optimizer for the neural network
    ...
    """
```

decoder should be rnn, and decoder_optimizer should be optimizer.

**Comment by jchernus** [comment]
Keen eye! You're correct. Would you be willing to create a pull request and then I can merge it into the codebase?
