### ISSUE TITLE
Undefined name

### ISSUE THREAD

**Issue by ATrefzer** [udacity/deep-learning-v2-pytorch#130]
In notebook: mnist-mlp/mnist_mlp_solution_with_validation.ipynb

print('Test Accuracy of %5s: N/A (no training examples)' % (classes[i]))

The variable classes is undefined. I think you mean str(i).

However, the line is never executed because all categories have samples.

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you
