### ISSUE TITLE
Unable to read/open a problematic dog image in Dog Breed Classifier project

### ISSUE THREAD

**Issue by cvanderw** [udacity/deep-learning-v2-pytorch#134]
One of the dog images in the train directory ("dogImages/train/098.Leonberger/Leonberger_06571.jpg") is causing issues when attempting to load via PIL. Specifically, the following error occurs: `OSError: image file is truncated (150 bytes not processed)`.

Since I've downloaded the project locally I could address this locally by moving out the offending file, but perhaps this should be fixed in the main repository here so that other students/users can benefit.

**Comment by cvanderw** [comment]
I'd be happy to send a pull request to remove the dog image, but perhaps the Udacity team can suggest a different fix.

**Comment by soswow** [comment]
@cvanderw either remote the image as you suggested or add this:
```python
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```
helped me

**Comment by cvanderw** [comment]
@soswow Thanks for the suggestion. That sounds like a great option. In that case the code should probably be updated to account for truncated images.
