### ISSUE TITLE
[Sentiment RNN] Dataflow in 'forward' method of Sentiment_RNN_Solution

### ISSUE THREAD

**Issue by th3ragex** [udacity/deep-learning-v2-pytorch#143]
The Sentiment_RNN_Solution notebook as well as the explanation in Lesson 8 suggest the following model forward method implementation:
```python       
[...]
        embeds = self.embedding(x)
        lstm_out, hidden = self.lstm(embeds, hidden)
    
        # stack up lstm outputs
        lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)
        
        # dropout and fully-connected layer
        out = self.dropout(lstm_out)
        out = self.fc(out)
        # sigmoid function
        sig_out = self.sig(out)
        
        # reshape to be batch_size first
        sig_out = sig_out.view(batch_size, -1)
        sig_out = sig_out[:, -1] # get last batch of labels
        
        # return last sigmoid output and hidden state
        return sig_out, hidden
```

The line `lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)"` resizes the LSTM output from `[batch_size, sequence_len, hidden_dim]` to `[batch_size*sequence_len, hidden_dim]` to match the Linear layers expectation. Most of the data will be discarded later on after the sigmoid:
```python  
        sig_out = sig_out.view(batch_size, -1)
        sig_out = sig_out[:, -1] # get last batch of labels
```
It suprises me that the creators of the model did not cut the unneeded data right after the LSTM layer to lower calculaction effors in the Linear layer.

E.g.: 
```python  
    def forward(self, x, hidden):
        emb = self.embedding(x)
        
        out, hidden = self.lstm(emb, hidden)
 
        #[50, 200, 512] => [50, 1, 512]
        #leave the output of the last word of each sequence
        out = out.narrow(1, -1, 1)
        out = torch.squeeze(out, 1)
        
        out = self.dropout(out)
        out = self.fc(out)
        
        # return last sigmoid output and hidden state
        sig_out = torch.sigmoid(out)
        sig_out = torch.squeeze(sig_out, 1)

        return sig_out, hidden
```

During my testing i wasn't able to measure a significant time difference between both implementations. 

Is PyTorch optimizing the overhead away? 
What is the best practice in regards of discarding data during the forward pass?

**Comment by zzyxzz** [comment]
It's different. You approach only uses the last state of the LSTM model to feed FC layer, however the notebook uses all the states of LSTM model to feed the FC layer.
