### ISSUE TITLE
Issues with project-tv-script-generation

### ISSUE THREAD

**Issue by mirceast** [udacity/deep-learning-v2-pytorch#149]
1. In helper.py at line 27 the first 81 characters of the data are eliminated: 
`text = text[81:]`
There is no notice to be ignored (as the comment at line 26 says), the text directly starts with "jerry: do you know what this is all about?"

2. In problem_unittests.py line 154:
`b = torch.from_numpy(a)` should be changed to `b = torch.from_numpy(a).type(torch.LongTensor)`
Not casting b to LongTensor means we have to cast it in the forward function. Doing that leads to another check for train_on_gpu, since after casting to LongTensor the resulting tensor will now be on the CPU. 

3. Maybe a little off topic, but the project rubric encourages us to use validation data for choosing the best model. That's cumbersome to do since we're not allowed to change anything in the `train_rnn` function.

**Comment by abhiojha8** [comment]
Happy to review changes and approve if you file a PR for 1 and 2. Thanks for the feedback on 3! We will incorporate that in future refreshes.
