### ISSUE TITLE
[sentiment-analysis-network] Sentiment_Classification_Solutions.ipynb weights initialization

### ISSUE THREAD

**Issue by Shitao** [udacity/deep-learning-v2-pytorch#15]
Potential improvement in init_network function under class SentimentNetwork:
To initialize weights between the hidden layer and output layer, self.output_nodes**-0.5 should be changed to self.hidden_nodes**-0.5.

**Comment by cezannec** [comment]
You're right! This should offer an improvement, and I'll take a closer look at this solution code to see if I should add this as a note or refactor the code. Thank you!

**Comment by cezannec** [comment]
Alright, I decided to add this weight initialization strategy as an alternate solution notebook in this repo. I also added some text in the classroom explaining this improvement, thank you!
