### ISSUE TITLE
Incorrect use of argwhere for indexing

### ISSUE THREAD

**Issue by gaurav1999** [udacity/deep-learning-v2-pytorch#156]
As per numpy docs : - (https://docs.scipy.org/doc/numpy/reference/generated/numpy.argwhere.html)
The output of argwhere is not suitable for indexing arrays. For this purpose use nonzero(a) instead.

In this:- https://github.com/udacity/deep-learning-v2-pytorch/blob/master/intro-neural-networks/gradient-descent/GradientDescent.ipynb

**Comment by abhiojha8** [comment]
Though we are late to respond, please feel free to open a PR for this. We will review the PR and then merge it.
