### ISSUE TITLE
Spelling mistake "of" -> "off"

### ISSUE THREAD

**Issue by Nick-the-BinaryTree** [udacity/deep-learning-v2-pytorch#161]
Ctrl-f for "start of" in:
https://github.com/udacity/deep-learning-v2-pytorch/blob/master/style-transfer/Style_Transfer_Exercise.ipynb

and

https://github.com/udacity/deep-learning-v2-pytorch/blob/master/style-transfer/Style_Transfer_Solution.ipynb

Code comment should read: "start off".
Under sub-header "Putting it all together".

**Comment by cezannec** [comment]
Thank you for noticing! This has been fixed
