### ISSUE TITLE
Issues with Bike Sharing Project

### ISSUE THREAD

**Issue by jaintj95** [udacity/deep-learning-v2-pytorch#165]
Is there any particular reason why the test cases fail for the following scenario?  
The **output_error_term** in backpropagation function is expected to be  
`output_error_term = error * final_outputs * (1 - final_outputs)`  
as per the exercises in the backpropagation lesson. However, the test cases fail and we have to work around the test cases by assigning the output_error_term to be equal to error like so:  
`output_error_term = error`  
Only then the test cases pass.

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you
