### ISSUE TITLE
[intro-to-pytorch]Part1 - Tensors in PyTorch(Exercises).ipynb Typo

### ISSUE THREAD

**Issue by starkblaze01** [udacity/deep-learning-v2-pytorch#172]
![errUdacity](https://user-images.githubusercontent.com/22374162/58753703-41ebef00-84e1-11e9-8f76-474bad29d4a8.png)
Typo in:
the number of columns in the first tensor must equal to the number of rows in the second **tensor** .

**Comment by gtyagi777** [comment]
torch.mm(features, weights.view(5, 1)

**Comment by gtyagi777** [comment]
torch.mm(features, weights.view(5, 1)

**Comment by abhiojha8** [comment]
Thanks! This has been resolved.
