### ISSUE TITLE
typo: [intro-to-pytorch]Part1 - Tensors in PyTorch(Exercises).ipynb

### ISSUE THREAD

**Issue by apapadaki** [udacity/deep-learning-v2-pytorch#175]
` Remember that for matrix multiplications, the number of columns in the first tensor must equal to the number of rows in the second column.`
it should be:

` Remember that for matrix multiplications, the number of columns in the first tensor must equal to the number of rows in the second tensor.`

**Comment by abhiojha8** [comment]
This has been fixed.
