### ISSUE TITLE
[intro-to-pytorch] fc_model module missing

### ISSUE THREAD

**Issue by rebeccaebarnes** [udacity/deep-learning-v2-pytorch#18]
The `fc_model.py` file is not included in the folder. This prevents [this](https://github.com/udacity/deep-learning-v2-pytorch/blob/master/intro-to-pytorch/Part%206%20-%20Saving%20and%20Loading%20Models.ipynb) notebook from executing without error. The module can be found [here](https://github.com/udacity/DL_PyTorch/blob/master/fc_model.py)

**Comment by mcleonard** [comment]
Thanks, fixing it now.

**Comment by mcleonard** [comment]
Fixed here: 4951aca43927fb28546431ca866ebc2a1c56469c
