### ISSUE TITLE
[project: TV script generation] import helper missing 

### ISSUE THREAD

**Issue by Berenice2018** [udacity/deep-learning-v2-pytorch#183]
Hi, 
In the following notebook: https://github.com/udacity/deep-learning-v2-pytorch/blob/master/project-tv-script-generation/dlnd_tv_script_generation.ipynb
cell  "Pre-process all the data and save it", the helper should already be imported, not in the following cell.

**Comment by abhiojha8** [comment]
Closing this as `helper.py` is present [here](https://github.com/udacity/deep-learning-v2-pytorch/tree/master/project-tv-script-generation)
