### ISSUE TITLE
Question about init_hidden in Character_Level_RNN_Solution

### ISSUE THREAD

**Issue by ghost** [udacity/deep-learning-v2-pytorch#187]
In Character_Level_RNN_Solution, you use net.init_hidden to initialize the hidden states for LSTM but I don't get why we need to initialize it at the beginning of each epoch. Isn't it supposed to be done before forwarding each batch? I wonder it is because input data are a continuous sequence and each batch are a part of the whole sequence. An explanation would be appreciated.

**Code:**
    for e in range(epochs):
        # initialize hidden state
        h = net.init_hidden(batch_size)
        for x, y in get_batches(data, batch_size, seq_length):
                .....

**Comment by mentalmushroom** [comment]
I would also like to add that according to PyTorch documentation on LSTM, if initial hidden state (h_0, c_0) is not provided, both h_0 and c_0 default to zero, so I don't see the point in manual zero initialization.

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks
