### ISSUE TITLE
Rename notebook from "Predicting_bike_sharing_data.ipynb" to "Your_first_neural_network.ipynb" 

### ISSUE THREAD

**Issue by souravs17031999** [udacity/deep-learning-v2-pytorch#206]
Please rename the file for Bike sharing prediction jupyter notebook from "Predicting_bike_sharing_data.ipynb" to "Your_first_neural_network.ipynb" 

If not renamed , then when submitting project from terminal on windows using command Udacity Submit , it gives 
"FileNotFoundERROR" : There is no Your_first_neural_network.ipynb file found.

**Comment by Simonmaignan** [comment]
I opened a [PR](https://github.com/udacity/deep-learning-v2-pytorch/pull/236) for this issue.
