### ISSUE TITLE
Delete __MACOSX from Dog Classification lfw.tgz achive

### ISSUE THREAD

**Issue by daniel-fudge** [udacity/deep-learning-v2-pytorch#217]
With the [project-dog-classification](https://github.com/udacity/deep-learning-v2-pytorch/tree/master/project-dog-classification) repo the [human dataset](http://vis-www.cs.umass.edu/lfw/lfw.tgz) contains unnecessary __MACOSX folder.

Please repackage the human dataset without the OS X temp folder.

**Comment by souravs17031999** [comment]
This folder is something which is created when Mac user creates zipped file.
This folder appears whenever some non mac user unzips the file.
I think Udacity must have packaged and zipped it from mac computer.
I don't think they can delete it (unless they upload it from another OS).
Any opinion ?

**Comment by daniel-fudge** [comment]
> This folder is something which is created when Mac user creates zipped file.
> This folder appears whenever some non mac user unzips the file.
> I think Udacity must have packaged and zipped it from mac computer.
> I don't think they can delete it (unless they upload it from another OS).
> Any opinion ?

Agreed.  They just need to zip from Linux or Windows or show hidden files on Mac and do not include when zipping.

**Comment by abhiojha8** [comment]
That folder is created in Mac by default. We can ignore that folder when using the dog and human datasets.
