### ISSUE TITLE
[intro-to-pytorch]Part 7 - Loading Image Data (Exercises)  trainloader/testLoader images are drawn foggy

### ISSUE THREAD

**Issue by yhhabiboglu** [udacity/deep-learning-v2-pytorch#22]
The pre-written code which is used to draw sample images from trainloader (also testloader) draws sample images foggy. Since the reference images in the cell which begins with the line  "Your transformed images should look something like this."  are nice I thought that I did something wrong. 

In the solution notebook,  `helper.imshow` is used with the `normalize=False`.

Changing `helper.imshow(images[ii], ax=ax)`  to `helper.imshow(images[ii], ax=ax, normalize=False)`can be helpful.

**Comment by mcleonard** [comment]
Fixed here: d23494dd36e5ab9d1547c3231a761c0a8ccdaab2

Thanks!
