### ISSUE TITLE
Part 5 : Inferences and Validation

### ISSUE THREAD

**Issue by andrewng88** [udacity/deep-learning-v2-pytorch#220]
https://i.imgur.com/ffUKixU.png

Based on this image, I don't quite understand the 

`equals = top_class == labels.view(*top_class.shape)`

part.

The `labels.view(-1,64)` method will be able to support broadcasting and end shape is 64,64 whereas when we use `.view(*top_class.shape)` it is still (64,1).

Thanks

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks
