### ISSUE TITLE
Reason np.random.choice generate unexpected result? 

### ISSUE THREAD

**Issue by s-arora-1987** [udacity/deep-learning-v2-pytorch#222]
Here is a part of skipgram exercise (Skip_Grams_Exercise.ipynb)
Exercise: Implement subsampling for the words in int_words. That is, go through int_words and discard each word given the probablility  𝑃(𝑤𝑖)  shown above. Note that  𝑃(𝑤𝑖)  is the probability that a word is discarded. Assign the subsampled data to train_words.

I tried to solve it two ways, and I get different results:

from collections import Counter
import random
import numpy as np
​
threshold = 1e-5
word_counts = Counter(int_words)
​
# discard some frequent words, according to the subsampling equation
# create a new list of words for training
train_words = []
for int_w in int_words:
    not_p = 1 - np.sqrt(threshold/(word_counts[int_w]/len(int_words)))
    sample = 1 if random.random() < (1-not_p) else 0
    if sample == 1:
        train_words.append(int_w)​
​
print(train_words[:30])

[5233, 3133, 58, 10571, 27349, 15067, 58112, 190, 10712, 2731, 3672, 0, 36, 97, 686, 7088, 5233, 320, 44611, 5233, 1134, 2621, 8983, 141, 4186, 5233, 1818, 6753, 7573, 11064]
​
threshold = 1e-5
word_counts = Counter(int_words)
​
# discard some frequent words, according to the subsampling equation
# create a new list of words for training
train_words = []
for int_w in int_words:
    not_p = 1 - np.sqrt(threshold/(word_counts[int_w]/len(int_words)))
    sample = np.random.choice([0,1],1,[not_p,1-not_p])[0]
    if sample == 1:
        train_words.append(int_w)
​​
print(train_words[:30])

[3080, 194, 1, 133, 0, 27349, 1, 0, 102, 854, 0, 15067, 58112, 1, 0, 3580, 0, 194, 190, 5, 10712, 214, 6, 2731, 6, 0, 708, 1, 40, 53]

Can anyone explain why I get more 0's in second case?

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks
