### ISSUE TITLE
Lesson 5 bug

### ISSUE THREAD

**Issue by dA505819** [udacity/deep-learning-v2-pytorch#225]
In the lesson 5, in every topic it's showing Due Date :- 1/1/1970

                                                                    Status:- Not Submitted
                                                                    Due at: Thu, Jan 1 5:30 am

I have started course last after 1 January only, So how is the above mentioned dates are possible?

**Comment by mdfazal** [comment]
Its a bug i guess because i didnt faced it. Many people have posted it in FB group also .

**Comment by dA505819** [comment]
Ya, I also thought it to be a bug.
