### ISSUE TITLE
Change of generator.next() to next(generator)

### ISSUE THREAD

**Issue by soni-ratnesh** [udacity/deep-learning-v2-pytorch#235]
In `dlnd_tv_script_generation`   
![Annotation 2020-03-19 165821](https://user-images.githubusercontent.com/46087108/77062992-f28c9600-6a02-11ea-969a-faf96fdb1466.png)
I guess it can be solved as python version 3.2 the syntax for the next() in-built function should be generator.__next__() or next(generator).

**Comment by abhiojha8** [comment]
This should work with the recommended version of Python in the classroom. We understand that .next() is not available in Python 3.2. We will keep this in mind while making future changes and upgrading everything to the latest versions.
