### ISSUE TITLE
[intro-neural-networks] Some issues with student-admissions 

### ISSUE THREAD

**Issue by chihhoang** [udacity/deep-learning-v2-pytorch#24]
A couple things I noticed about the "Analyzing Student Data" notebook:
1. In the first plot, there is a small bug and it's not showing up. It just shows the metadata on the plot object. Adding "%matplotlib inline" before import matplotlib seems to fix this (credits to MSJose in the Slack channel).
2. The sigmoid_prime function is not used anywhere. It should not be there since we calculate the derivative directly in the error_term_formula function.
3. There is a typo in the train_nn function. Since we declare the error equation as -(y - y_hat)*sigmoid_prime(x), when we update the gradient it should be del_w -= error_term * x.  The solution gets around this by removing the negative sign in the error equation. My point here is that if we follow the error equation in the notebook which has the negative sign, the training won't work with the way the weights are updated currently in the train_nn function.
Another way we could fix this without changing the test function is to get rid of the negative sign in the error equation.

**Comment by cezannec** [comment]
I see what you mean. I've updated the code to include clearer instructions and two possible solutions to the error term formula. Thank you!
