### ISSUE TITLE
Hidden State Propagation in Sentiment-RNN-Solution

### ISSUE THREAD

**Issue by guptv93** [udacity/deep-learning-v2-pytorch#244]
In Sentiment-RNN-Solution each minibatch consists of 50 reviews each 200 words long. However at the end of training on each mini-batch we keep pass the hidden state vector to the next mini-batch. This to be doesn't make sense. Why should the context transfer from one mini-batch to the other? Each mini-batch has different reviews and the reviews don't span over multiple mini-batches. This, to me, made sense in Char-RNN but doesn't make sense here. Can someone please explain?

**Comment by zmy** [comment]
Agree, totally confused by the implementation too.

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you
