### ISSUE TITLE
scipy.misc.imsave is depricated

### ISSUE THREAD

**Issue by amanvishnani** [udacity/deep-learning-v2-pytorch#247]
https://github.com/udacity/deep-learning-v2-pytorch/blob/3a95d118f9df5a86826e1791c5c100817f0fd924/cycle-gan/helpers.py#L75

Currently, this piece of code throws an exception `module 'scipy.misc' has no attribute 'imsave'`

Possible cause `scipy.misc.imsave` is [deprecated](https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.misc.imsave.html).

Possible [fix](https://stackoverflow.com/questions/19991665/my-scipy-misc-module-appears-to-be-missing-imsave): `imageio.imwrite('filename.jpg', array)`

**Comment by abhiojha8** [comment]
This should work with the version of scipy recommended for this course. However, it would be great if you could add a PR for this. We will review and approve the changes.
