### ISSUE TITLE
How can I run the GAN MNIST on GPU?

### ISSUE THREAD

**Issue by monajalal** [udacity/deep-learning-v2-pytorch#251]
I have an NVIDIA 2070 GPU and I want to use GAN MNIST. I have installed the latest GPU compatible version of PyTorch and set the device to CUDA but still, the code uses CPU. How can I make the code use the GPU without major changes?
https://github.com/udacity/deep-learning-v2-pytorch/blob/master/gan-mnist/MNIST_GAN_Solution.ipynb

**Comment by Bhuvan-21** [comment]
transfer your model and data to cuda
use 
model.cuda()
images = images.cuda()
and similarly for fake images
