### ISSUE TITLE
cifar10_cnn_exercise: final result visualization doesn't work on GPU

### ISSUE THREAD

**Issue by rogalskim** [udacity/deep-learning-v2-pytorch#258]
This is the same problem as was reported in #121, but in another file. The mentioned issue was referring to the **solution** notebook, where the problem is now fixed. 

However, it still occurs in the **exercise** notebook. I've decided to create a new issue to bring this to your attention.

The affected line is here:
https://github.com/udacity/deep-learning-v2-pytorch/blob/3a95d118f9df5a86826e1791c5c100817f0fd924/convolutional-neural-networks/cifar-cnn/cifar10_cnn_exercise.ipynb#L496

Because the `images` Tensor is moved to the GPU when running in a CUDA environment, the line causes a `TypeError`.

A simple fix, would be to use the `images.cpu()` method in the `imshow` call.

Someone else has already submitted a pull request with a similar solution, here: #226.

**Comment by Sturzgefahr** [comment]
This is also an issue in the file cifar10_cnn_augmentation.
