### ISSUE TITLE
Model is always saying 'Negative Review' in "Sentiment_RNN_Solution"

### ISSUE THREAD

**Issue by ash-13** [udacity/deep-learning-v2-pytorch#259]
Model is always saying 'Negative Review' as we can see on bottom of the page. Weather it's negative or positive.
![Screenshot 2020-05-12 at 2 35 38 AM](https://user-images.githubusercontent.com/41446634/81611765-4612d300-93f9-11ea-9790-4d77f249f2e7.png)

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks
