### ISSUE TITLE
helper file missing at project-face-generation

### ISSUE THREAD

**Issue by ricoms** [udacity/deep-learning-v2-pytorch#262]
[This](https://github.com/udacity/deep-learning-v2-pytorch/tree/master/project-face-generation) lacks the helper module used by students.

**Comment by ricoms** [comment]
I found helper file [here](https://github.com/optimistanoop/DLND-Face-Generation/blob/master/helper.py).

The notebook that the student send is not in any way similar to the posted here. Is this up to date? Me, as udacity's reviewer, what should I do. The rubric also does not match with the student's submission...

**Comment by abhiojha8** [comment]
We are closing out the issue because there are no enhancements proposed here.
