### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by njuul** [udacity/deep-learning-v2-pytorch#273]
Not opening in Python - an have tried around a million ways to solve it with o succes. How can I run this file - and, hence, do the exercise?

**Comment by Tylersuard** [comment]
Did you try opening it in Google Colab?  https://colab.research.google.com/github/EliShayGH/cycle-gan-image2image-translation/blob/master/CycleGAN_Image2Image_Translation.ipynb

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks
