### ISSUE TITLE
requirements.txt doesn't list torch or version numbers

### ISSUE THREAD

**Issue by dwisdom0** [udacity/deep-learning-v2-pytorch#274]
I think `torch` is supposed to be in `requirements.txt`. There also aren't any version numbers in `requirements.txt`, so it's hard to know what version of the packages will work with the code in the notebooks.

**Comment by abhiojha8** [comment]
You can do `pip freeze > requirements. txt ` in the classroom workspace terminal to get the packages used by Udacity in the classroom.

Other than that, I agree that the requirements.txt file should ideally have versions. We will update that in the next iteration.
