### ISSUE TITLE
Picture of Leaky ReLU is actually a picture of a ReLU

### ISSUE THREAD

**Issue by bfeeny** [udacity/deep-learning-v2-pytorch#278]
In the notebooks:
```
MNIST_GAN_Exercise.ipynb
MNIST_GAN_Solution.ipynb
```

Under the section:
`Define the Model` -> `Leaky ReLU`

A picture is presented, labeled: "LeakyReLU Activation Function".  The function presented is actually the function of ReLU, not LeakyReLU.  If one argues that there is in fact a slope present for negative values, I would say it is so subtle, that the intuition will escape a novice student, and there should be some exaggeration.  When you look at typical pictures of Leaky ReLU functions you will find much more apparent slopes, and I would say that unless you have a large screen, high resolution and you zoom significantly, you will not obviously see that what is being shown is actually a Leaky ReLU function.

**Comment by abhiojha8** [comment]
We will update this in the next revision. Thanks for the feedback!
