### ISSUE TITLE
[intro-to-pytorch][Part 3 - Training Neural Networks] 

### ISSUE THREAD

**Issue by Macheddy** [udacity/deep-learning-v2-pytorch#29]
Make use of the already downloaded image MNIST dataset from part-2 instead of downloading it again to ~/.pytorch/MNIST_data/

**Comment by mcleonard** [comment]
I set it so we're downloading MNIST to `~/.pytorch/MNIST_data` in Part 2 and Part 3

commit here: f7eab40968ea95fd33f463cecaec4bb8cd2669fa
