### ISSUE TITLE
A follow-up question about: Issue with dimension in last output of Discriminator structure in CycleGan notebook (#72)

### ISSUE THREAD

**Issue by Xi-Ronnie-Chen** [udacity/deep-learning-v2-pytorch#292]
Is there a reason for these two steps? Why not go for the single step of creating the final layer with a kernel size of 8, padding 0 and actually have it output just one value?

_Originally posted by @christian-steinmeyer in https://github.com/udacity/deep-learning-v2-pytorch/issues/72#issuecomment-640414059_

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks
