### ISSUE TITLE
Normalization 

### ISSUE THREAD

**Issue by saikrishnadas** [udacity/deep-learning-v2-pytorch#296]
Each color channel was normalized separately, the means are [0.485, 0.456, 0.406] and the standard deviations are [0.229, 0.224, 0.225].

How did you find those normalization values and can i use them in all cases other than cat and dog ?

**Comment by kHarshit** [comment]
These are Imagenet's mean and std. Check this answer https://stackoverflow.com/a/57533806/6210807

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks
