### ISSUE TITLE
Wrong test loss and accuracy 

### ISSUE THREAD

**Issue by saikrishnadas** [udacity/deep-learning-v2-pytorch#297]
![Screenshot (136)](https://user-images.githubusercontent.com/30836867/102457139-41399000-4068-11eb-85bf-1bcfdbed1862.png)

 i get test loss 0 and accuracy 1 and its constant for all epochs.

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks
