### ISSUE TITLE
[intro-to-pytorch] typo in the notebook part 2

### ISSUE THREAD

**Issue by mdmahendri** [udacity/deep-learning-v2-pytorch#30]
> You can access the weight and bias tensors **once the network once it's create** at net.hidden.weight and net.hidden.bias.

it should be or similar to the sentence below right?
> You can access the weight and bias tensors **once the network is created** at net.hidden.weight and net.hidden.bias.`

**Comment by cezannec** [comment]
Yes! Thank you, I just fixed this to read "You can access the weight and bias tensors once the network (`net`) is created with `net.hidden.weight` and `net.hidden.bias`."
