### ISSUE TITLE
CycleGAN Error: One of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by Tylersuard** [udacity/deep-learning-v2-pytorch#300]
RuntimeError                              Traceback (most recent call last)

<ipython-input-31-7dbbc7a8bdd8> in <module>()
      1 n_epochs = 200 # keep this small when testing if a model first works, then increase it to >=1000
      2 
----> 3 losses = training_loop(dataloader_X, dataloader_Y, test_dataloader_X, test_dataloader_Y, n_epochs=n_epochs)

2 frames

/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
    130     Variable._execution_engine.run_backward(
    131         tensors, grad_tensors_, retain_graph, create_graph,
--> 132         allow_unreachable=True)  # allow_unreachable flag
    133 
    134 

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 512, 4, 4]] is at version 4; expected version 3 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks
