### ISSUE TITLE
Intro to Pytorch - Part 1 - Tensors in PyTorch (Exercises).ipynb has solutions

### ISSUE THREAD

**Issue by tacticfox** [udacity/deep-learning-v2-pytorch#312]
Hello,

I'm currently going through the course Intro to Pytorch, which is amazing. Thank you.
I think in the Part 1 - Tensors in PyTorch (Exercises).ipynb notebook, the solutions are already included. For example when calculating the torch.sum() as the first exercise. Unless I'm mistaking something here.

Best regards
Lukas

**Comment by ronny-udacity** [comment]
Thank you for reporting the issue. The solutions have been removed from the exercise notebook.
