### ISSUE TITLE
Typo in project "sentiment-analysis-network", file: "Sentiment_Classification_Projects.ipynb"

### ISSUE THREAD

**Issue by JeffDuf** [udacity/deep-learning-v2-pytorch#313]
**project**:"sentiment-analysis-network"

**file**: "Sentiment_Classification_Projects.ipynb"

**Line**: 324

**Sentence with typo**: "* Right now, 1 is considered neutral, but the absolute value of the postive-to-negative rations of very postive word..."

**Issue description**: The word "rations" should probably be "ratios".

**Comment by abhiojha8** [comment]
This typo is fixed in the [notebook](https://github.com/udacity/deep-learning-v2-pytorch/blob/master/sentiment-analysis-network/Sentiment_Classification_Projects.ipynb).
