### ISSUE TITLE
Intro To Pytorch Download Issues

### ISSUE THREAD

**Issue by mitchjablonski** [udacity/deep-learning-v2-pytorch#316]
In the intro to pytorch section, the references to download the MNIST data set fail.  It would appear, this is tied to the pytorch issue, https://github.com/pytorch/vision/issues/1938 .  There is a workaround that is used in the convolutional neural networks section, proposing that this is also used in the intro to pytorch notebooks that download the MNIST data. https://github.com/udacity/deep-learning-v2-pytorch/blob/master/convolutional-neural-networks/mnist-mlp/mnist_mlp_exercise.ipynb

**Comment by mitchjablonski** [comment]
This issue is also relevant to the autoencoder segment, where mnist data is used.

**Comment by ronny-udacity** [comment]
Thank you for the PR.
