### ISSUE TITLE
Broken link in project-dog notebook

### ISSUE THREAD

**Issue by JeffDuf** [udacity/deep-learning-v2-pytorch#318]
Git: deep-learning-v2-pytorch\project-dog-classification\dog_app.ipynb

The following link is broken:
- _Before writing the function, make sure that you take the time to learn how to appropriately pre-process tensors for pre-trained **models in the PyTorch documentation._** --> http://pytorch.org/docs/stable/torchvision/models.html
Should be re-linked to this: https://pytorch.org/vision/stable/models.html

**Comment by abhiojha8** [comment]
Thanks for the updated link. We have fixed it.
