### ISSUE TITLE
Erreur Pendant le chargement Notebook

### ISSUE THREAD

**Issue by AminaF12** [udacity/deep-learning-v2-pytorch#334]
Unreadable Notebook: C:\Users\hp\deep-learning-v2-pytorch\project-bikesharing\Predicting_bike_sharing_data.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')

**Comment by ronny-udacity** [comment]
Thanks for reporting this issue. However, I can't replicate this issue as the project jupyter notebook seems to be working just fine.

Please refer to this StackOverflow [discussions](https://stackoverflow.com/questions/32103772/unreadable-notebook-notjsonerrornotebook-does-not-appear-to-be-json-u-n) for the potential cause of the "'Notebook does not appear to be JSON" error message.
