### ISSUE TITLE
[intro-neural-networks/student-admissions/StudentAdmissions.ipynb] 

### ISSUE THREAD

**Issue by leigh-plt** [udacity/deep-learning-v2-pytorch#35]
Section:
TODO:  Make dummy variables for rank
one_hot_data = pd.get_dummies(data, columns=['rank'])

TODO: Drop the previous rank column 
We don't need drop or use drop_first=True in dummy function

If use drop_first=True for avoid linearity We need hint like: "use drop_first"

**Comment by cezannec** [comment]
Thanks! In the notebook, I've just added a hint/link to pandas drop function, which should help.
