### ISSUE TITLE
#TODO Exercise in Intro To Torch Part 8 is already solved

### ISSUE THREAD

**Issue by cerepos** [udacity/deep-learning-v2-pytorch#37]
The notebook "Part 8 - Transfer Learning (Exercises).ipynb" in "into-to-pytorch" folder has the TODO exercise about transformations already solved, even though it is not a "solution" notebook.

**Comment by mcleonard** [comment]
Really? Oh dang. I'll look into that.

**Comment by dJani97** [comment]
The issue is valid, I proposed a change in the following pull request:
[https://github.com/udacity/deep-learning-v2-pytorch/pull/55](url)

**Comment by mcleonard** [comment]
Fixed in this commit: 883eb15a91f80c10064be8e2b6b13527060f4607
