### ISSUE TITLE
[intro-to-pytorch/Part 8 - Transfer Learning (Exercises).ipynb]

### ISSUE THREAD

**Issue by UrszulaCzerwinska** [udacity/deep-learning-v2-pytorch#393]
Thank you for great tutorials. 

I would like to understand how you define the input size to the linear layer to be 1024. 

I don't undersand how it relates to the image size [3, 224, 224].

We saw in the previous lessons that the input size to a linear net would be 3*224*224.

Thank you in advance !

**Comment by ronny-udacity** [comment]
We only define the `classifier` layers, which contains 2 `fully connected` layer.
The input to the first classifier's layer takes the output from the pre-trained `densenet` instead of the image data.
