### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3584x7 and 25088x4096)

### ISSUE THREAD

**Issue by HamdiTarek** [udacity/deep-learning-v2-pytorch#396]
I am trying two different images and I am getting this error, this is the size of the two images after loading them: 
torch.Size([1, 3, 400, 444])
torch.Size([1, 3, 400, 444])

**Comment by ronny-udacity** [comment]
The error message shows the dimension shapes of the two matrices can't be multiplied. The matrix multiplication requires the shapes to be (m,n) and (n, p),
