### ISSUE TITLE
[intro-to-pytorch]Part 7 - Loading Image Data  - transform

### ISSUE THREAD

**Issue by ivigamberdiev** [udacity/deep-learning-v2-pytorch#44]
In second code cell Exercises Notebook you assign variable with name 'transforms'. It's overwrite this variable, which contain import from torchvision and can produce Exception after second execution code cell. You have a solution for this bug in Solution Notebook.

**Comment by dJani97** [comment]
That's a problem that I also encountered when I tried to run the notebook.
It's easy to fix but it would be nice to see it fixed in the repo too :)

**Comment by cezannec** [comment]
Yes, thanks! Just merged your fix
