### ISSUE TITLE
[CycleGan]_missing relu activation function to the output of ResidualBlock()

### ISSUE THREAD

**Issue by hpkhanh1610** [udacity/deep-learning-v2-pytorch#51]
Hi,

In the CycleGan_solution notebook, in function **forward()** in class ResidualBlock, why don't we apply the **relu activation** function to the out_2 - the output of each residual block? As I have seen in the image in the description, it says that we have the addition first F(x) + x, followed by a **relu activation** function.

**Comment by cezannec** [comment]
Good question! I followed what they did in the original PyTorch implementation, here: https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py You can see in the ResnetBlock code that they only apply a ReLu to the first convolutional layer, and this code seems to work well.

**Comment by CuriousCat-7** [comment]
It looks like one author made a mistake and the whole internet follow him. Now, every cycle-gan pytorch open source codes use this wrong ResNet block.
