### ISSUE TITLE
Indentation issue in TV script problem_unittests.py file

### ISSUE THREAD

**Issue by saadtazi** [udacity/deep-learning-v2-pytorch#6]
the following lines [here](https://github.com/udacity/deep-learning-v2-pytorch/blob/master/project-tv-script-generation/problem_unittests.py#L62), [here](https://github.com/udacity/deep-learning-v2-pytorch/blob/master/project-tv-script-generation/problem_unittests.py#L69-L70) and [here](https://github.com/udacity/deep-learning-v2-pytorch/blob/master/project-tv-script-generation/problem_unittests.py#L80-L81) causes the following type of error:

```
Traceback (most recent call last):

  File "/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-5-9be11ce52ce0>", line 1, in <module>
    import problem_unittests as tests

  File "/notebooks/project-tv-script-generation/problem_unittests.py", line 65
    assert not (int_to_vocab_word_set - vocab_to_int_word_set),\
    ^
IndentationError: unexpected indent
```

I can open a PR if you want, but I wasn't sure if it was intentional or not. Let me know. I'd be more than happy to open a PR!

**Comment by yannRavels** [comment]
+1, and I have a student who had issues because of this

**Comment by cezannec** [comment]
Oh dear, must have been a copy-paste issue. The indentation should be fixed now, thank you so much for catching this! The experience should be better for all students, now :)
