### ISSUE TITLE
Part 2- Neural Networks in Pytorch -Helper function issue

### ISSUE THREAD

**Issue by Surojit88** [udacity/deep-learning-v2-pytorch#61]
Hello ,

The following code snippet below raises an error when executed;

```
# Grab some data 
dataiter = iter(trainloader)
images, labels = dataiter.next()

# Resize images into a 1D vector, new shape is (batch size, color channels, image pixels) 
images.resize_(64, 1, 784)
# or images.resize_(images.shape[0], 1, 784) to automatically get batch size

# Forward pass through the network
img_idx = 0
ps = model.forward(images[img_idx,:])

img = images[img_idx]
**helper.view_classify(img.view(1, 28, 28), ps)**

```

Error:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-99-3760ccc5c3dd> in <module>()
>      12 
>      13 img = images[img_idx]
> ---> 14 helper.view_classify(img.view(1, 28, 28), ps)
> 
> AttributeError: module 'helper' has no attribute 'view_classify'

Please suggest.

Regards
Surojit

**Comment by carlodavid012** [comment]
you need to put the helper.py file in your working directory

**Comment by carlodavid012** [comment]
try this !wget https://raw.githubusercontent.com/udacity/deep-learning-v2-pytorch/3bd7dea850e936d8cb44adda8200e4e2b5d627e3/intro-to-pytorch/helper.py
