### ISSUE TITLE
[intro-to-pytorch]Part 1 - Tensors in PyTorch (Exercises).ipynb 

### ISSUE THREAD

**Issue by leigh-plt** [udacity/deep-learning-v2-pytorch#65]
Add information and example about operator "@" which override for matrix product in numpy and pytorch.
Operation: torch.mm(x, y) equal x @ y. For numpy same: np.matmul(a, b) equal a @ b.
This notation not common but you can see it sometime. 
And some trick for weights.view(5,1) you can get using notation: weights.t() - shorter.

**Comment by abhiojha8** [comment]
We suggest you refer to the Knowledge hub and reach out to your assigned mentor for user-specific issues. 
Thanks
