### ISSUE TITLE
Missing images in [Intro to Pytorch]Part 2 - Neural Networks in PyTorch (Exercises).ipynb and Neural Networks in PyTorch (Solution).ipynb

### ISSUE THREAD

**Issue by amarjeetsingh1999** [udacity/deep-learning-v2-pytorch#67]
The images that are to be displayed under the "Activation Functions" and "Your Turn to Build a Network" are not displayed. Rather the code is displayed there.
![image](https://user-images.githubusercontent.com/35170799/48970356-3a7af300-f031-11e8-8a6e-ece8f85ece35.png)

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you
