### ISSUE TITLE
Broken link to wikipedia page about uniform distribution

### ISSUE THREAD

**Issue by Bjarten** [udacity/deep-learning-v2-pytorch#7]
This link shows as broken in my jupyter notebook (version 5.7.0):
```[uniform distribution](https://en.wikipedia.org/wiki/Uniform_distribution_(continuous%29)```
However, the link displays fine in the online notebook viewer http://nbviewer.jupyter.org/.

Proposed fixed link:
```[uniform distribution](https://en.wikipedia.org/wiki/Uniform_distribution_(continuous))```

It also shows up broken when typed here:
original:
[uniform distribution](https://en.wikipedia.org/wiki/Uniform_distribution_(continuous%29)
fixed:
[uniform distribution](https://en.wikipedia.org/wiki/Uniform_distribution_(continuous))

Occurrences:

    "A [uniform distribution](https://en.wikipedia.org/wiki/Uniform_distribution_(continuous%29) has the equal probability of picking any number from a set of numbers. We'll be picking from a continuous distribution, so the chance of picking the same number is low. We'll use NumPy's `np.random.uniform` function to pick random numbers from a uniform distribution.\n",
https://github.com/udacity/deep-learning-v2-pytorch/blob/139e8b9b5a88142108dd47c4e4d39c20816074e1/weight-initialization/weight_initialization_exercise.ipynb#L283

    "A [uniform distribution](https://en.wikipedia.org/wiki/Uniform_distribution_(continuous%29) has the equal probability of picking any number from a set of numbers. We'll be picking from a continuous distribution, so the chance of picking the same number is low. We'll use NumPy's `np.random.uniform` function to pick random numbers from a uniform distribution.\n",
https://github.com/udacity/deep-learning-v2-pytorch/blob/139e8b9b5a88142108dd47c4e4d39c20816074e1/weight-initialization/weight_initialization_solution.ipynb#L313

**Comment by cezannec** [comment]
Hello! Thank you for catching this, the link is now fixed and pointed to the general page on uniform distributions.
