### ISSUE TITLE
Recurrent-Neural-Networks / char-rnn / Character_Level_RNN

### ISSUE THREAD

**Issue by Jon-5** [udacity/deep-learning-v2-pytorch#73]
When not using CUDA, there is a type error. It might be due to PyTorch better reducing input data prior to training, and so the target specified for the CrossEntropy / NLL Loss needs to be cast to torch.LongTensor as opposed to the torch.IntTensor that was being input as the target for the loss function

the minimal necessary changes in the module train:

loss = criterion(output, targets.view(batch_size*seq_length).type(torch.LongTensor))

val_loss = criterion(output, targets.view(batch_size*seq_length).type(torch.LongTensor))

**Comment by Fernandohf** [comment]
I can confirm the same error using cuda.
> RuntimeError: Expected object of type torch.cuda.LongTensor but found type torch.cuda.IntTensor for argument #2 'target'

An alternative solution could be using ``long()`` method:
```python
loss = criterion(output, targets.view(batch_size*seq_length).long())
val_loss = criterion(output, targets.view(batch_size*seq_length).long())
```

**Comment by jchernus** [comment]
Thanks folks!!
