### ISSUE TITLE
StudentAdmissions - Error Term Formula

### ISSUE THREAD

**Issue by RahulRagesh** [udacity/deep-learning-v2-pytorch#75]
The error term formula is given as (y-yhat)*sigmoid_prime(x). Shouldn't it be (y-yhat)/(yhat(1-yhat)) * sigmoid_prime(x)? Isn't it derived from this chain rule application dE/dyhat * dyhat/dh?

**Comment by abhiojha8** [comment]
We have updated this in the notebook.
