### ISSUE TITLE
deep-learning-v2-pytorch/intro-to-pytorch/Part 7 - Loading Image Data (Solution).ipynb

### ISSUE THREAD

**Issue by djdanielsson** [udacity/deep-learning-v2-pytorch#83]
I think it could be helpful for students to see an example of a working network that can classify correctly from the training solution that is given in this section. For those who may have tried but were unable to get their code to work, might be able to learn what they may have done wrong. I was disappointed when I got to this section and no solution was given for this part and all that was said was this is hard and you probably wont get it, but that isn't very helpful for those trying to learn.

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you
