### ISSUE TITLE
Part - 6 Saving and Loading Models

### ISSUE THREAD

**Issue by smyrbdr** [udacity/deep-learning-v2-pytorch#84]
I think, the thing the instructor actually wants to do with the last 2 codes, is to save the first model with its network architecture. But since he defines right before another model variable with new network architecture, he saves and loads a model which is not trained yet at all.

So the last 3rd code cell which was created to throw an error should be for example like this instead;

```python
# Try this
model_1 = fc_model.Network(784, 10, [400, 200, 100])
# This will throw an error because the tensor sizes are wrong!
model_1.load_state_dict(state_dict)
```

So that the next 2 code cells (the last 2 code cells) then will save exactly the trained model with its network architecture, not an un-trained new model.

```python
checkpoint = {'input_size': 784,
              'output_size': 10,
              'hidden_layers': [each.out_features for each in model.hidden_layers],
              'state_dict': model.state_dict()}

torch.save(checkpoint, 'checkpoint.pth')
```

This issue makes the topic somewhat confusing.

**Comment by lleiou** [comment]
Hi I'm also confused by the jupyter notebook, but what's the point of saving the original model again in the last 2 cells? Thanks!

**Comment by abhiojha8** [comment]
Thanks for the feedback. We will incorporate this when we plan a refresh.
