### ISSUE TITLE
Issue with helper

### ISSUE THREAD

**Issue by miniamisha** [udacity/deep-learning-v2-pytorch#88]
I am using colab and already !pip install helper , but I facing the error AttributeError: module 'helper' has no attribute 'imshow' and also 
AttributeError: module 'helper' has no attribute 'view_classify'
What is wrong with helper??

**Comment by nvs-abhilash** [comment]
Hi @miniamisha the helper is a custom script in the repository, not any package. You can find the script here: [https://github.com/udacity/deep-learning-v2-pytorch/blob/master/intro-to-pytorch/helper.py](https://github.com/udacity/deep-learning-v2-pytorch/blob/master/intro-to-pytorch/helper.py).

You can use this hack to get the script in your pwd:
```jupyter
!wget https://raw.githubusercontent.com/udacity/deep-learning-v2-pytorch/3bd7dea850e936d8cb44adda8200e4e2b5d627e3/intro-to-pytorch/helper.py
```

**Comment by githubssd** [comment]
hi @miniamisha, 
simply download the helper.py from  https://github.com/udacity/deep-learning-v2-pytorch/blob/master/intro-to-pytorch/helper.py and upload it to google colab, this will solve your issue

or You may have he helper.py file in intro-to-pytorch folder if you have downloaded that repo.

Enjoy!

**Comment by jchernus** [comment]
Thanks for helping her out!

**Comment by oudarjya718** [comment]
Im  in jupyter lab , getting AttributeError: ```module 'helper' has no attribute 'view_classify'```

**Comment by imwaqasahmed** [comment]
hi there,
ps=F.softmax(logits,dim=1)
import helper
helper.view_classify(img.view(1,28,28),ps,version="MNIST")
python shows no error but also it doesnt plot anything
what am i missing

**Comment by sarimurrab** [comment]
helper used here is not from pip but a .py file, which is available in the repo
and view_classify is declared inside that. Simply paste the helper.py where your project is located.

**Comment by saadiqueanwar** [comment]
Even after pasting the file in my pwd, it shows the same error...
ie. AttributeError: module 'helper' has no attribute 'view_classify'

**Comment by davidefiocco** [comment]
Hi @saadiqueanwar after you put the file in your current working dir e.g. with the solution above

`!wget https://raw.githubusercontent.com/udacity/deep-learning-v2-pytorch/3bd7dea850e936d8cb44adda8200e4e2b5d627e3/intro-to-pytorch/helper.py`

Just restart your runtime and re-execute the imports. That should do the trick.

**Comment by linusmotu** [comment]
Also having the same problem as @imwaqasahmed, i cloned the whole repo, everything works, but once i need to import and use helper functions, nothing happens, no plot. Everything breaks afterwards, i try to run it again and it says **no module named helper**.

**Comment by EtemKavak** [comment]
> Hi @saadiqueanwar @oudarjya718 after you put the file in your current working dir e.g. with the solution above
> 
> `!wget https://raw.githubusercontent.com/udacity/deep-learning-v2-pytorch/3bd7dea850e936d8cb44adda8200e4e2b5d627e3/intro-to-pytorch/helper.py`
> 
> Just restart your runtime and re-execute the imports. That should do the trick.
> 
> As an alternative, once you have issued the `wget` command above, do
> 
> ```
> import importlib
> importlib.reload(helper)
> ```
> 
> and then run the cell again.

that worked for me, issue resolves. 
thanks for the fix :)

**Comment by Manish2261** [comment]
AttributeError: module 'helper' has no attribute 'display_stats'
It is the error I am getting, I have even downloaded the helper.py and it is also not having the 'display_stats' function defined, If anyone could guide me in solving this?

**Comment by HNA113** [comment]
after creating helper.py file, how can i import it to jupyter notebook?
pls help me out

**Comment by SivaHemanth24** [comment]
Create a class named helper and copy the code from helper.py into this class

**Comment by mostafiz67** [comment]
> AttributeError: module 'helper' has no attribute 'display_stats'
> It is the error I am getting, I have even downloaded the helper.py and it is also not having the 'display_stats' function defined, If anyone could guide me in solving this?

I am also facing the same problem! Did you solve the problem?

**Comment by RadCopperman** [comment]
qf.download_csv_data(ticker='CNR', 
                     start_date='2017-01-01', 
                     end_date='2018-12-31', 
                     path='TSX/daily/CNR.csv')

AttributeError: module 'helper_functions' has no attribute 'download_csv_data'

Anyone can help?
Thanks,

**Comment by mozillakab** [comment]
For those who use Python on Desktop:

- Go to https://github.com/udacity/deep-learning-v2-pytorch/blob/master/intro-to-pytorch/helper.py
- copy all the content
- add plt.show at the end.
- The call the function classify without helper. (because not import is used. The function is within your file) : view_classify(img.view(1,28,28),ps)


def view_classify(img, ps, version="MNIST"):
    ''' Function for viewing an image and it's predicted classes.
    '''
    ps = ps.data.numpy().squeeze()

    fig, (ax1, ax2) = plt.subplots(figsize=(6,9), ncols=2)
    ax1.imshow(img.resize_(1, 28, 28).numpy().squeeze())
    ax1.axis('off')
    ax2.barh(np.arange(10), ps)
    ax2.set_aspect(0.1)
    ax2.set_yticks(np.arange(10))
    if version == "MNIST":
        ax2.set_yticklabels(np.arange(10))
    elif version == "Fashion":
        ax2.set_yticklabels(['T-shirt/top',
                            'Trouser',
                            'Pullover',
                            'Dress',
                            'Coat',
                            'Sandal',
                            'Shirt',
                            'Sneaker',
                            'Bag',
                            'Ankle Boot'], size='small');
    ax2.set_title('Class Probability')
    ax2.set_xlim(0, 1.1)

    plt.tight_layout()
    plt.show()
