### ISSUE TITLE
Issue on Sentiment_RNN_Solution notebook forward() function.

### ISSUE THREAD

**Issue by hpkhanh1610** [udacity/deep-learning-v2-pytorch#9]
Hi,

In the Sentiment_RNN_Solution, in the **forward()** when building the network, in the part:
     **# reshape to (hidden_dim, batch_size, n_classes)
       sig_out = sig_out.view(-1, batch_size, self.output_size)
       sig_out = sig_out[0] # get last batch of labels***

Instead of reshaping and pick the last batch like in the solution above, why don't we just use **sig_out = sig_out[ : , -1, : ]** with only 1 line. This picks the sigmoid output from the end of each batch.

In addition, as I have seen the output size after the **self.fc(lstm_out)**, the size is (batch=50, seq_len=200, output=2), if we reshape using **sig_out.view(-1, batch_size, self.output_size)**, how can we get **hidden_dim** be the first dimension like in the lecture as well as in the notebook's comment? And when we reshape like that, although we get the correct size (seq_len, batch_size, output_size), the order of numbers will be mixed up and wrong, this just reshapes to rows by rows. I mean, before reshaping, for each batch of 50, there are 200x2 values corresponding to that batch. Then we just use normal reshape, we get size of (seq_len, batch_size, output_size), but now the sequences and batches are not related to each other anymore, their values are mixed now. We need some method similar like **transpose** or **numpy array.T** in order to conserve their corresponding values.

By the way, suppose we can get the correct size (seq_len, batch, n_classes=2) with their corresponding values after resizing, why do we want to use **sig_out[0]**? In this case, **sig_out[-1]** is correct because we just want to select the **sigmoid output** from the last word of each batch.

**Comment by cezannec** [comment]
Hello! 

Thanks for noticing this, the shape and slicing of this data was indeed wrong and the solution code has been updated to fix this. Thank you!
